[pytest]
# 1. Правила именования (чтобы pytest понимал, где искать тесты)
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# 2. Регистрация маркировок (чтобы убрать те самые Warning в консоли)
# Формат: название_метки: краткое описание
markers =
    smoke: критически важные тесты (проверка основного пути)
    regression: тесты для полной проверки функционала (регрессия)
    authentication: тесты, связанные с логином и правами доступа
    users: тесты для работы с API пользователей

# 3. Настройки вывода (опционально, но удобно)
# -v делает вывод подробным, -s позволяет видеть print() в консоли
addopts = -v -s